#undef RGBLED_NUM
#define RGBLED_NUM 3
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 16
#define RGBLIGHT_VAL_STEP 16
#define RGBW
#define RGBLIGHT_LAYERS
#define RGBLIGHT_SLEEP
#define RGB_DI_PIN F6
